---
definitions:
  steps:
    - step: &test-code
        name: Test step
        image: golang:1.14
        script:
          - go get -v
          - go test -timeout 30s -cover ./...
        caches:
          - go
    - step: &lint-code
        name: Code lint step
        image: golang:1.14
        script:
          - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin "latest"
          - go get -v
          - golangci-lint run
        caches:
          - go
  caches:
    go: $GOPATH/pkg

pipelines:
  default:
    - step: *test-code
    - step: *lint-code
